name: Deploy to Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Create source bundle
        run: |
          zip -r eb_source_bundle.zip . -x node_modules/**\* data.sqlite tmp_uploads/**\* .git/**\*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload bundle to S3
        run: |
          aws s3 cp eb_source_bundle.zip s3://${{ secrets.EB_S3_BUCKET }}/eb-deployments/eb_source_bundle.zip

      - name: Create application version
        run: |
          VERSION_LABEL="gh-${{ github.sha }}"
          aws elasticbeanstalk create-application-version --application-name "${{ secrets.EB_APP_NAME }}" --version-label "$VERSION_LABEL" --source-bundle S3Bucket=${{ secrets.EB_S3_BUCKET }},S3Key=eb-deployments/eb_source_bundle.zip

      - name: Update environment
        run: |
          VERSION_LABEL="gh-${{ github.sha }}"
          aws elasticbeanstalk update-environment --environment-name "${{ secrets.EB_ENV_NAME }}" --version-label "$VERSION_LABEL"
