name: Deploy Backend to Azure Container Apps (Simplified)

on:
  push:
    branches: [ main, master ]
    paths: [ 'azure-backend/**' ]
  workflow_dispatch:

env:
  REGISTRY_LOGIN_SERVER: datacategorizationregistry.azurecr.io
  REGISTRY_USERNAME: datacategorizationregistry

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v4
      with:
        context: ./azure-backend
        push: true
        tags: |
          ${{ env.REGISTRY_LOGIN_SERVER }}/backend:${{ github.sha }}
          ${{ env.REGISTRY_LOGIN_SERVER }}/backend:latest
        file: ./azure-backend/Dockerfile

    - name: Image built successfully
      run: |
        echo "✅ Container image built and pushed successfully!"
        echo "📍 Image: ${{ env.REGISTRY_LOGIN_SERVER }}/backend:${{ github.sha }}"
        echo "🚀 You can now manually deploy this image to your Container App"