name: Deploy to Azure Functions

on:
  push:
    branches: [ main ]
    paths: [ 'azure-backend/**' ]
  pull_request:
    branches: [ main ]

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure-backend'
  NODE_VERSION: '18.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        npm ci

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'data-categorization-backend'
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}