name: Automated Backend CI/CD to Azure Container Apps

on:
  push:
    branches: [ main, master ]
    paths: [ 'server.js', 'src/**', 'views/**', 'package.json', 'package-lock.json', 'Dockerfile' ]
  workflow_dispatch:

env:
  REGISTRY_LOGIN_SERVER: datacategorizationregistry.azurecr.io
  REGISTRY_USERNAME: datacategorizationregistry
  IMAGE_NAME: fullstack-app
  CONTAINER_APP_NAME: data-categorization-backend
  RESOURCE_GROUP: data-categorization-rg

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
        file: ./Dockerfile
        platforms: linux/amd64

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Apps
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "🚀 Updating Container App with new image..."
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --revision-suffix auto-$(date +%s)
          
          echo "✅ Container App updated successfully!"
          echo "📍 New image: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          echo "🌐 Backend URL: https://data-categorization-backend.whitebush-303875e0.eastus.azurecontainerapps.io"

    - name: Verify deployment
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          echo "🔍 Checking deployment status..."
          az containerapp show \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --query "{Status:properties.runningStatus, Image:properties.template.containers[0].image}" \
            --output table
          
          echo "📋 Recent logs:"
          az containerapp logs show \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --tail 10